version: '3'
services:
  companies_web:
    container_name: companies_web
    image: nginx:1.22.1
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - companies_php
      - companies_pgsql
  companies_php:
    container_name: companies_php
    build: ./infrastructure/php-fpm
    env_file:
      - ./.env
    volumes:
      - .:/var/www/html
      - ./infrastructure/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  companies_pgsql:
    image: postgres:15.0
    container_name: companies_pgsql
    ports:
      - 2345:5432
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  pgsql_data:
    driver: local
